spring.application.name=admin
server.port=8522

# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=NRP
spring.datasource.password=nrp
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://LIN-PG02TMYV.corp.capgemini.com:8761/eureka/
eureka.instance.prefer-ip-address=true
